.github/workflows/test-events-Pythia-Isr-Dat.yaml, .github/workflows/test-events-Pythia-Isr-Hadron.yaml, .github/workflows/test-events-Pythia-Isr-Parton.yaml, src/jet/Matter.cc
This brings JETSCAPE PR 183 to X-SCAPE and applies Matter's random seed fix.
=> Eloss Matter seed corr

config/jetscape_user_pbpb_grid.xml
Removes obsolete option in AA user config
=> brings change from JETSCAPE 3.6.2 to X-SCAPE

.github/workflows/test-events-brick.yaml
This adds the Brick Matter Lbt test to the automated tests that run on pushes and pull requests.
=> Includes Brick Matter Lbt Automated Test

.github/workflows/plot_observables.yaml, .github/workflows/smash_test_completes.yaml, .github/workflows/test-build-external.yaml, .github/workflows/test-events-PbPb.yaml, .github/workflows/test-events-Pythia-Isr-Dat.yaml, .github/workflows/test-events-Pythia-Isr-Hadron.yaml, .github/workflows/test-events-Pythia-Isr-Parton.yaml, .github/workflows/test-events-brick.yaml, .github/workflows/test-events-pp.yaml, README.md, config/jetscape_main.xml, config/jetscape_user_pbpb_grid.xml, src/framework/JetScapeConstants.h, src/hadronization/ColorlessHadronization.cc, src/hadronization/ColorlessHadronization.h, src/hydro/Brick.cc, src/initialstate/epemGun.cc, src/initialstate/epemGun.h, src/jet/ISRRotation.cc, src/jet/ISRRotation.h, src/jet/Matter.cc, src/jet/Matter.h, src/jet/iMATTER.cc, src/jet/iMATTER.h
This PR merges the XSCAPE-1.1.2-RC branch to main for the public release.
=> Xscape 1.1.2 rc

.github/ISSUE_TEMPLATE/01-bug_report.yml, .github/ISSUE_TEMPLATE/02-enhancement.yml, .github/ISSUE_TEMPLATE/config.yml
This PR implements GitHub Issue Template Forms for bug reports and enhancements.
Since this PR only adds YAML files for repository management on GitHub and doesn't touch any of the X-SCAPE source code, no version number update is applied.
=> Implements GitHub Issue Template Forms

config/jetscape_main.xml, src/hadronization/iSpectraSamplerWrapper.cc
implements PR 204 from JETSCAPE in X-SCAPE.  Adds iSS parameters to JETSCAPE xml file and updates the framework wrapper so that important parameters can be passed via XML to iSS.
=> add iSS parameters to JETSCAPE xml file

config/jetscape_main.xml, src/framework/LiquefierBase.cc, src/framework/LiquefierBase.h
This adds new parameters to liquefier, applying PR 205 from JETSCAPE.
=> adds new parameters to liquefier

src/afterburner/SmashWrapper.h
applying changes from JETSCAPE PR 229: https://github.com/JETSCAPE/JETSCAPE/pull/229
=> Fix infinite loop when input for SMASH is empty

src/hadronization/HybridHadronization.cc
applying changes from JETSCAPE PR 230: https://github.com/JETSCAPE/JETSCAPE/pull/230
=> Fix bug when not decaying hadrons Hybrid Hadronization (Pythia)

config/jetscape_main.xml, external_packages/get_freestream-milne.sh, external_packages/get_music.sh, src/preequilibrium/FreestreamMilneWrapper.cc
incorporates [JETSCAPE PR 237](https://github.com/JETSCAPE/JETSCAPE/pull/237) and closes [JETSCAPE Issue 236](https://github.com/JETSCAPE/JETSCAPE/issues/236)
=> Fix density rotation bug / FS automatic parameter determination

config/jetscape_main.xml, external_packages/get_freestream-milne.sh, external_packages/get_music.sh, src/preequilibrium/FreestreamMilneWrapper.cc
=> Revert "Fix density rotation bug / FS automatic parameter determination"

src/hadronization/iSpectraSamplerWrapper.cc, src/hydro/MusicWrapper.cc
=> fix the clean up order when nReUseHydro > 1

src/framework/SurfaceCellInfo.h, src/hadronization/iSpectraSamplerWrapper.cc, src/hydro/MusicWrapper.cc
This applies PR 244 from JETSCAPE 3.6.7
=> pass net bayon density

config/jetscape_main.xml, config/publications_config/arXiv_2011.01430/jetscape_user_AA_2011.01430.xml, src/preequilibrium/FreestreamMilneWrapper.cc
apply PR 246 from JETSCAPE 3.6.7
=> Additional free streaming parameters in XML

config/jetscape_main.xml, examples/FinalStateHadrons.cc, examples/FinalStatePartons.cc, src/framework/JetScapeWriterFinalStateStream.cc, src/framework/JetScapeWriterFinalStateStream.h
apply PR 242 from JETSCAPE 3.6.7
=> option to filter on final state hadrons status code

config/jetscape_user_PbPb_hard_nPDF.xml
apply PR 249 from JETSCAPE 3.6.7
=> Remove nPDF settings from AA hard paper XML and copy to separate XML

config/jetscape_main.xml, external_packages/get_ipglasma.sh, src/initialstate/IPGlasmaWrapper.cc, src/preequilibrium/Glasma.cc, src/preequilibrium/Glasma.h
This applies JETSCAPE 3.6.7 PR 253 to X-SCAPE.
=> update the Glasma preEq wrapper

src/framework/InitialState.cc, src/initialstate/TrentoInitial.cc, src/jet/Matter.cc, src/preequilibrium/FreestreamMilneWrapper.cc
This PR applies PR 254 from JETSCAPE 3.6.7
=> Ritoban datta/inital stage orientation fixing

src/preequilibrium/Glasma.h
=> Fix glasma time to remove time shift in stored evolution

.github/workflows/test-build-external.yaml, CMakeLists.txt, external_packages/README.md
=> Make IP-Glasma CMake flag similar to other external codes

config/jetscape_main.xml, src/framework/InitialState.cc, src/framework/InitialState.h, src/framework/JetScapeEventHeader.h, src/framework/JetScapeWriterFinalStateStream.cc, src/framework/JetScapeWriterFinalStateStream.h, src/initialstate/TrentoInitial.cc, src/initialstate/TrentoInitial.h
=> Centrality table update

config/jetscape_main.xml, src/framework/JetScapeWriterFinalStateStream.cc
=> Bug fix for filtering final state particles in writer

.github/workflows/smash_test_completes.yaml, .github/workflows/test-build-external.yaml, .github/workflows/test-build-macos-native.yaml, .github/workflows/test-build-nPDF.yaml, .github/workflows/test-events-Pythia-Isr-Dat.yaml, .github/workflows/test-events-Pythia-Isr-Hadron.yaml, .github/workflows/test-events-Pythia-Isr-Parton.yaml, .github/workflows/test-events-brick.yaml, .github/workflows/test-events-pp.yaml, README.md, config/jetscape_user_nPDF_test.xml, external_packages/get_lhapdf.sh
Applies PR 267 from JETSCAPE 3.7
=> Add Support for LHAPDF and Documentation

src/framework/JetScapeWriterQnCalculator.cc
This applies PR #270 from JETSCAPE 3.7
=> fix Qnvector issue

src/hydro/HydroFromFile.cc
Apply PR 274 from JETSCAPE 3.7.1
=> Vz fix IP-GLASMA Grid Saved

.github/workflows/test-events-Pythia-Isr-Hadron.yaml, config/jetscape_main.xml, external_packages/get_3dglauber.sh, src/framework/HardProcess.cc, src/framework/InitialState.h, src/hydro/MusicWrapper.cc, src/hydro/MusicWrapper.h, src/initialstate/MCGlauberWrapper.cc, src/initialstate/MCGlauberWrapper.h
This applies PR 112 from X-SCAPE COMP to X-SCAPE public's XSCAPE-1.2-RC branch.
I ran the tests offline before submitting this PR and the test_out_final_state_hadrons.dat file is different. Do we expect these changes to produce different results? If so, I can update the test_out_final_state_hadrons reference file.
=> Passing qcd string list to music

src/reader/JetScapeReaderFinalStateHadrons.cc, src/reader/JetScapeReaderFinalStateHadrons.h
Reads the hadron files so you dont need to do it in python
=> Adding FInalStateHadronsc++ reader

external_packages/get_3dglauber.sh, src/initialstate/MCGlauberWrapper.cc
- Print out all the model parameters after they are set by the xml. 
- Reinitialize the Glauber object to ensure the reset parameters are effective
=> update the 3D-Glauber interface

config/jetscape_main.xml, config/jetscape_user_brick_hybrid_hadronization.xml, src/hydro/Brick.cc, src/hydro/Brick.h
Adding option to set flow velocity for brick module. I've used it for checking flow effects before as have other people so I figured it made sense to roll this out publicly.
=> Adding brick flow options

src/hadronization/HybridHadronization.cc
Changing PYTHIA setting read in order to prevent particle data changes from getting overwritten
=> changing read in order to prevent overwriting
