- external_packages/README.md
This pull request is just a documentation update, adding details to the external packages README showing how to build IP-Glasma with the jetscape/base:stable Docker image.
> updated IP-Glasma instructions

- src/framework/FourVector.h
This PR applies the changes to FourVector.h from JETSCAPE-COMP.
The function updates themselves were already here in X-SCAPE, but this keeps the spacing and formatting in sync with the JETSCAPE file.
> includes FourVector updates from JETSCAPE-COMP

- src/jet/LBT.cc
- src/jet/Matter.cc
This PR applies Ritoban's pT-broadening fix from JETSCAPE 3.6.1.
"A new status code "101" is added to LBT.cc to tackle partons which has broadened. Now, energy loss module LBT doesn't push back such partons. The energy loss module Matter.cc has some extra logic condition in the broadening section, otherwise the same broadening parton was pushed in twice."
> applies Ritoban's pT-broadening fix from JETSCAPE

- config/jetscape_main.xml
- src/framework/JetScapeConstants.h
- src/hadronization/ColorlessHadronization.cc
- src/hadronization/ColorlessHadronization.h
- src/hydro/Brick.cc
- src/initialstate/epemGun.cc
- src/initialstate/epemGun.h
- src/jet/ISRRotation.cc
- src/jet/ISRRotation.h
- src/jet/Matter.cc
- src/jet/Matter.h
- src/jet/iMATTER.cc
- src/jet/iMATTER.h
This PR brings JETSCAPE 3.6.2 change to X-SCAPE.
Reverts making Lambda_QCD an XML parameter, move back to JS constants,
Removes initial state pointer from Brick.cc
> brings JETSCAPE 3.5.2 change to X-SCAPE

- src/jet/Matter.cc
This PR brings Ritoban's JETSCAPE 3.6.2 PR to X-SCAPE:
Fixing logic related to broadening. Now if a parton is not apt to split virtuality-wise, then the parton is pushed back only once if broadening is on+ recoil is off+qhat>0. Otherwise the parton in not pushed back. This is the same as it was in JETSCAPE-3.6.
> Fixing logic related to broadening

- src/framework/PreequilibriumDynamics.cc
- src/hydro/MusicWrapper.cc
This moves the pre-equilibrium pointer in the MusicWrapper into the else case, where it is already checked to be properly initialized. This avoids segmentation faults.
I also implemented the initialization of the start and end time variables in the pre-equilibrium part of the code.
@chunshen1987 Is this correct? I took this from the Jetscape code. If I understood this correctly, it is needed in case no `NullPreDynamics` is used?
> Fix music wrapper bug

- .github/workflows/plot_observables.yaml
- .github/workflows/smash_test_completes.yaml
- .github/workflows/test-build-external.yaml
- .github/workflows/test-events-PbPb.yaml
- .github/workflows/test-events-Pythia-Isr-Dat.yaml
- .github/workflows/test-events-Pythia-Isr-Hadron.yaml
- .github/workflows/test-events-Pythia-Isr-Parton.yaml
- .github/workflows/test-events-brick.yaml
- .github/workflows/test-events-pp.yaml
- README.md
- src/afterburner/SmashWrapper.h
- src/hadronization/HybridHadronization.cc
merges XSCAPE-1.1.4-RC to main for the X-SCAPE 1.1.4 release.
> Xscape 1.1.4 rc

- .github/workflows/plot_observables.yaml
- .github/workflows/smash_test_completes.yaml
- .github/workflows/test-build-external.yaml
- .github/workflows/test-build-macos-native.yaml
- .github/workflows/test-events-PbPb.yaml
- .github/workflows/test-events-Pythia-Isr-Dat.yaml
- .github/workflows/test-events-Pythia-Isr-Hadron.yaml
- .github/workflows/test-events-Pythia-Isr-Parton.yaml
- .github/workflows/test-events-brick.yaml
- .github/workflows/test-events-pp.yaml
- README.md
- external_packages/gtl/include/GTL/GTL.h
- external_packages/gtl/src/bid_dijkstra.cpp
- external_packages/gtl/src/dijkstra.cpp
This PR resolves the compilation issue when using Clang 16 by removing the binary_function inheritance in the GTL library.
GitHub Actions workflows are also added to test that JETSCAPE compiles on native Mac hardware. Separate workflows use Clang 15 and Clang 16, so both compilers are verified.
This PR incorporates [JETSCAPE PR 234](https://github.com/JETSCAPE/JETSCAPE/pull/234)
> remove gtl binary_function & add macOS workflow

- examples/test_music_files/music_input
This implements JETSCAPE PR 231:
When both pre-equilibrium and hydro outputs evolution history to memory, one needs to set output_evolution_every_N_timesteps to 1 in music_input. It is because the free-streaming module does not support skipping time step output evolution.
> fixed the time step for output evolution history

- config/jetscape_user_MUSICMainClockTest.xml
- config/jetscape_user_iMATTERMCGlauberMUSIC.xml
There were still a few `useHybridHad` floating around in XS. They are now removed.
> Remove useHybridHad flag from xml

- .github/workflows/smash_test_completes.yaml
- .github/workflows/test-build-external.yaml
- .github/workflows/test-build-macos-native.yaml
- .github/workflows/test-events-PbPb.yaml
- .github/workflows/test-events-Pythia-Isr-Dat.yaml
- .github/workflows/test-events-Pythia-Isr-Hadron.yaml
- .github/workflows/test-events-Pythia-Isr-Parton.yaml
- .github/workflows/test-events-brick.yaml
- .github/workflows/test-events-pp.yaml
- CMakeLists.txt
This modernizes the CMakeLists syntax requiring C++17 so it will work on newer compilers.
> update C++17 requirement CMakeLists syntax

- .github/workflows/smash_test_completes.yaml
- .github/workflows/test-build-external.yaml
- .github/workflows/test-build-macos-native.yaml
- .github/workflows/test-events-PbPb.yaml
- .github/workflows/test-events-Pythia-Isr-Dat.yaml
- .github/workflows/test-events-Pythia-Isr-Hadron.yaml
- .github/workflows/test-events-Pythia-Isr-Parton.yaml
- .github/workflows/test-events-brick.yaml
- .github/workflows/test-events-pp.yaml
- external_packages/README.md
This PR adds IP-Glasma to the external packages automated build test and updates the installation instructions in the external packages README.
I will change the Docker tag references in the test workflows from v1.10 to stable when the v1.10 image is tagged as stable for the release.
> Add IP-Glasma to Build Test and Update README Instructions

- config/jetscape_main.xml
- src/framework/JetScapeConstants.h
- src/hadronization/ColorlessHadronization.cc
- src/hadronization/ColorlessHadronization.h
- src/initialstate/epemGun.cc
- src/initialstate/epemGun.h
- src/jet/ISRRotation.cc
- src/jet/ISRRotation.h
- src/jet/Matter.cc
- src/jet/Matter.h
- src/jet/iMATTER.cc
- src/jet/iMATTER.h
This adds the `Lambda_QCD` as XML parameter.
@cparker24 Should we also add the `Qs` to the XML? I forgot to mention this in the meeting this morning.
> XML Lambda_QCD parameter

- config/jetscape_main.xml
- examples/FinalStateHadrons.cc
- examples/FinalStatePartons.cc
- src/framework/HardProcess.cc
- src/framework/JetScapeEventHeader.h
- src/framework/JetScapeWriterFinalStateStream.cc
- src/framework/JetScapeWriterFinalStateStream.h
- src/reader/JetScapeReader.cc
- src/reader/JetScapeReader.h
Apply PR 266 from JETSCAPE 3.7
> add vertex information to final state hadron and partons

- src/hadronization/iSpectraSamplerWrapper.cc
This applies PR 269 from JETSCAPE 3.7
> explicitly clear the iSS and HadronList every time passing hadrons from iSS to the JETSCAPE framework

- CMakeLists.txt
- src/CMakeLists.txt
This transfers PR [#272](https://github.com/JETSCAPE/JETSCAPE/pull/272/files) from JETSCAPE to X-SCAPE.
> CMake IP-Glasma flag

- src/framework/PreequilibriumDynamics.h
- src/hydro/MusicWrapper.cc
@ritobandatta and @cparker24, This PR fixes the issue that the energy loss modules cannot access the pre-equilibrium information.
@ritobandatta You can go on with the tests for the rotation bug fix now.
> Fix accessibility of pre-equilibrium evolution

- src/framework/JetScapeWriterQnCalculator.cc
- src/framework/JetScapeWriterQnCalculator.h
This PR brings changes from JETSCAPE PR 277 to X-SCAPE.
Write more info in the Qn vector output file. (https://github.com/JETSCAPE/JETSCAPE/issues/276, https://github.com/JETSCAPE/JETSCAPE/pull/277)
> Write more info in the Qn vector output file

- config/jetscape_main.xml
- examples/convert_binary_to_ASCII_output.py
- src/framework/JetScapeWriterFinalStateStream.cc
- src/framework/JetScapeWriterFinalStateStream.h
This adds a binary output mode for the final state hadron/parton outputs. It comes in the following form:
```
File header:
1 int: Binary output version (1 at the moment)
4 int: status codes to skip (can store 4 codes to skip [default 666], if more are skipped, then they are ignored and a warning is printed)
Event header:
1 int: event_number
7 float: event_weight, event_plane_angle, vx, vy, vz, centrality, pt_hat (vx/vy/vz are the vertex location)
1 int: num_particles
num_particles particle blocks:
2 int: pid, status
4 float: e, px, py, pz
File footer:
2 float: sigmaGen, sigmaErr
```
This output includes the maximum amount of information that can be written in the current form of the ASCII output.
@raymondEhlers This PR also removes the writing of the `event_weight` and `pt_hat` in the …
> Binary writer

- src/framework/FluidDynamics.cc
- src/hydro/MusicWrapper.cc
This adds:
- Reset the `hydro_status` to `NOT_START` after each event to allow for the initialization of the next hydro event.
- Add a safety check to enter pre-equilibrium block only if the initial profile is set to 42 (Trento+FS).
> Fix hydro multiple events

- CMakeLists.txt
Per @chunshen1987's suggestion, this PR provides a more meanginful error message when SMASH is turned on in CMAKE but not found, which may occur when using Apptainer/Singularity if the SMASH_DIR environment variable is not correctly set.
> update cmake error message for when SMASH is turned on but not found
